USE [InvoiceDB]
GO

/****** Object:  Table [dbo].[INVOICEHEADER]    Script Date: 7/27/2022 2:24:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INVOICEHEADER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[INVOICENUMBER] [int] NULL,
	[CUSTOMERNUMBER] [int] NULL,
	[INVOICEDT] [datetime] NULL,
	[AMOUNT] [money] NULL,
	[VOIDFLAG] [bit] NULL,
 CONSTRAINT [PK__INVOICEH__3214EC2792B8A0AC] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF__INVOICEHE__VOIDF__108B795B]  DEFAULT ((0)) FOR [VOIDFLAG]
GO

ALTER TABLE [dbo].[INVOICEHEADER]  WITH CHECK ADD  CONSTRAINT [FK_INVOICEHEADER_INVOICEHEADER] FOREIGN KEY([ID])
REFERENCES [dbo].[INVOICEHEADER] ([ID])
GO

ALTER TABLE [dbo].[INVOICEHEADER] CHECK CONSTRAINT [FK_INVOICEHEADER_INVOICEHEADER]
GO


